### PR TITLE
Add local dev server

### PR DESCRIPTION
**Pull request by simeg**
- Add a local development server with livereload using the Grunt tasks `grunt-contrib-connect` and `connect-livereload`
- Add demo link to README
- Add instructions on how to start local development server to README

**Notes:**
- I commented out line 97 in `gruntfile.js` out as the javascript files doesn't need to get build every time the site reloads
- Lines 68-69 in `index.html` should be removed from production, I'm not sure how to do it
- You should find a way to handle the import of the file `deployment` in `gruntfile.js` as I had to comment out the import to be able to run anything using `grunt`

**Questions:**
1. I'd like to add a lint task to this project which will require some work just to get the syntax looking the same, so before I begin I'd just like to get an OK from you. If it's an OK from you then please share your indentation preferences as it's obvious we're working in different IDEs (my IDE, WebStorm, shows that all indentation looks good but looking at the files in this commit on GitHub I see that's not the case).
2. Can the files in `src/js/dependencies` be installed via npm instead?

And finally, thanks for a very cool web app!

### CODE REVIEW

**Comment by scottwarren** [comment]
For question one, an [`.editorconfig`](http://editorconfig.org/) would be a good option

**Comment by hatsumatsu** [comment]
Thanks for contributing! There are a lot going on in this PR.

I just fixed the readme part and added `.editorconfig` in the meantime, really good thing to have in the tool stack!

Including a local server and live reload is not so much my cup of tea since my version lives inside a Apache-based localhost... 

I would be interested in seeing how dependencies can be handled via `npm`, maybe you can make a PR just for this purpose?

**Comment by simeg** [comment]
Nice job with the `.editorconfig` 👍.

About the dev server, why can't both options be available? Having a dev server based on `grunt` wont disturb your setup and improves the development environment for everyone else.

I'll see what I can do about the dependencies!

**Comment by scottwarren** [comment]
Not that I have any say in the matter, but for me, having the smallest barrier of entry to start contributing will help, even if that means you add LIve Reload and then never use it :+1:

**Pull request closed without merging**
