### PR TITLE
Adds local development base

### PR DESCRIPTION
**Pull request by scottwarren**
It would be good if you can show me an example .deployment file of what yours looks like, so that I can commit a base one that will make this work out of the box without exposing your files.

### CODE REVIEW

**Comment by scottwarren** [comment]
This pull request adds what #1 has merged with it around local development

**Comment by scottwarren** [comment]
Could also use some of the stuff that #3 has done (or use it in it's entirety)

**Comment by hatsumatsu** [comment]
This should be fixed in [4afb4b7](https://github.com/hatsumatsu/108/commit/4afb4b7c421aa0f2a501a6b12a81880cd8494ac4)

**Comment by scottwarren** [comment]
Woo, thanks!

**Pull request closed without merging**
